// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageData.proto

package com.pinkpig.entity.protobuf;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.pinkpig.entity.protobuf.MessageData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *定义第1个属性，SysHeader类型
     * </pre>
     *
     * <code>optional .com.pinkpig.entity.protobuf.SysHeader sysHeader = 1;</code>
     */
    boolean hasSysHeader();
    /**
     * <pre>
     *定义第1个属性，SysHeader类型
     * </pre>
     *
     * <code>optional .com.pinkpig.entity.protobuf.SysHeader sysHeader = 1;</code>
     */
    com.pinkpig.entity.protobuf.MessageProto.SysHeader getSysHeader();
    /**
     * <pre>
     *定义第1个属性，SysHeader类型
     * </pre>
     *
     * <code>optional .com.pinkpig.entity.protobuf.SysHeader sysHeader = 1;</code>
     */
    com.pinkpig.entity.protobuf.MessageProto.SysHeaderOrBuilder getSysHeaderOrBuilder();

    /**
     * <pre>
     *定义第2个属性，字节数组类型
     * </pre>
     *
     * <code>optional bytes content = 2;</code>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * <pre>
   *定义消息类型
   * </pre>
   *
   * Protobuf type {@code com.pinkpig.entity.protobuf.MessageData}
   */
  public  static final class MessageData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.pinkpig.entity.protobuf.MessageData)
      MessageDataOrBuilder {
    // Use MessageData.newBuilder() to construct.
    private MessageData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageData() {
      content_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MessageData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.pinkpig.entity.protobuf.MessageProto.SysHeader.Builder subBuilder = null;
              if (sysHeader_ != null) {
                subBuilder = sysHeader_.toBuilder();
              }
              sysHeader_ = input.readMessage(com.pinkpig.entity.protobuf.MessageProto.SysHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sysHeader_);
                sysHeader_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {

              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pinkpig.entity.protobuf.MessageProto.internal_static_com_pinkpig_entity_protobuf_MessageData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pinkpig.entity.protobuf.MessageProto.internal_static_com_pinkpig_entity_protobuf_MessageData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pinkpig.entity.protobuf.MessageProto.MessageData.class, com.pinkpig.entity.protobuf.MessageProto.MessageData.Builder.class);
    }

    public static final int SYSHEADER_FIELD_NUMBER = 1;
    private com.pinkpig.entity.protobuf.MessageProto.SysHeader sysHeader_;
    /**
     * <pre>
     *定义第1个属性，SysHeader类型
     * </pre>
     *
     * <code>optional .com.pinkpig.entity.protobuf.SysHeader sysHeader = 1;</code>
     */
    public boolean hasSysHeader() {
      return sysHeader_ != null;
    }
    /**
     * <pre>
     *定义第1个属性，SysHeader类型
     * </pre>
     *
     * <code>optional .com.pinkpig.entity.protobuf.SysHeader sysHeader = 1;</code>
     */
    public com.pinkpig.entity.protobuf.MessageProto.SysHeader getSysHeader() {
      return sysHeader_ == null ? com.pinkpig.entity.protobuf.MessageProto.SysHeader.getDefaultInstance() : sysHeader_;
    }
    /**
     * <pre>
     *定义第1个属性，SysHeader类型
     * </pre>
     *
     * <code>optional .com.pinkpig.entity.protobuf.SysHeader sysHeader = 1;</code>
     */
    public com.pinkpig.entity.protobuf.MessageProto.SysHeaderOrBuilder getSysHeaderOrBuilder() {
      return getSysHeader();
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString content_;
    /**
     * <pre>
     *定义第2个属性，字节数组类型
     * </pre>
     *
     * <code>optional bytes content = 2;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sysHeader_ != null) {
        output.writeMessage(1, getSysHeader());
      }
      if (!content_.isEmpty()) {
        output.writeBytes(2, content_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sysHeader_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSysHeader());
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, content_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.pinkpig.entity.protobuf.MessageProto.MessageData)) {
        return super.equals(obj);
      }
      com.pinkpig.entity.protobuf.MessageProto.MessageData other = (com.pinkpig.entity.protobuf.MessageProto.MessageData) obj;

      boolean result = true;
      result = result && (hasSysHeader() == other.hasSysHeader());
      if (hasSysHeader()) {
        result = result && getSysHeader()
            .equals(other.getSysHeader());
      }
      result = result && getContent()
          .equals(other.getContent());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasSysHeader()) {
        hash = (37 * hash) + SYSHEADER_FIELD_NUMBER;
        hash = (53 * hash) + getSysHeader().hashCode();
      }
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.pinkpig.entity.protobuf.MessageProto.MessageData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pinkpig.entity.protobuf.MessageProto.MessageData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pinkpig.entity.protobuf.MessageProto.MessageData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pinkpig.entity.protobuf.MessageProto.MessageData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pinkpig.entity.protobuf.MessageProto.MessageData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pinkpig.entity.protobuf.MessageProto.MessageData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pinkpig.entity.protobuf.MessageProto.MessageData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.pinkpig.entity.protobuf.MessageProto.MessageData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pinkpig.entity.protobuf.MessageProto.MessageData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pinkpig.entity.protobuf.MessageProto.MessageData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.pinkpig.entity.protobuf.MessageProto.MessageData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *定义消息类型
     * </pre>
     *
     * Protobuf type {@code com.pinkpig.entity.protobuf.MessageData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.pinkpig.entity.protobuf.MessageData)
        com.pinkpig.entity.protobuf.MessageProto.MessageDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pinkpig.entity.protobuf.MessageProto.internal_static_com_pinkpig_entity_protobuf_MessageData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pinkpig.entity.protobuf.MessageProto.internal_static_com_pinkpig_entity_protobuf_MessageData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pinkpig.entity.protobuf.MessageProto.MessageData.class, com.pinkpig.entity.protobuf.MessageProto.MessageData.Builder.class);
      }

      // Construct using com.pinkpig.entity.protobuf.MessageProto.MessageData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (sysHeaderBuilder_ == null) {
          sysHeader_ = null;
        } else {
          sysHeader_ = null;
          sysHeaderBuilder_ = null;
        }
        content_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pinkpig.entity.protobuf.MessageProto.internal_static_com_pinkpig_entity_protobuf_MessageData_descriptor;
      }

      public com.pinkpig.entity.protobuf.MessageProto.MessageData getDefaultInstanceForType() {
        return com.pinkpig.entity.protobuf.MessageProto.MessageData.getDefaultInstance();
      }

      public com.pinkpig.entity.protobuf.MessageProto.MessageData build() {
        com.pinkpig.entity.protobuf.MessageProto.MessageData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pinkpig.entity.protobuf.MessageProto.MessageData buildPartial() {
        com.pinkpig.entity.protobuf.MessageProto.MessageData result = new com.pinkpig.entity.protobuf.MessageProto.MessageData(this);
        if (sysHeaderBuilder_ == null) {
          result.sysHeader_ = sysHeader_;
        } else {
          result.sysHeader_ = sysHeaderBuilder_.build();
        }
        result.content_ = content_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pinkpig.entity.protobuf.MessageProto.MessageData) {
          return mergeFrom((com.pinkpig.entity.protobuf.MessageProto.MessageData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pinkpig.entity.protobuf.MessageProto.MessageData other) {
        if (other == com.pinkpig.entity.protobuf.MessageProto.MessageData.getDefaultInstance()) return this;
        if (other.hasSysHeader()) {
          mergeSysHeader(other.getSysHeader());
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pinkpig.entity.protobuf.MessageProto.MessageData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pinkpig.entity.protobuf.MessageProto.MessageData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.pinkpig.entity.protobuf.MessageProto.SysHeader sysHeader_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.pinkpig.entity.protobuf.MessageProto.SysHeader, com.pinkpig.entity.protobuf.MessageProto.SysHeader.Builder, com.pinkpig.entity.protobuf.MessageProto.SysHeaderOrBuilder> sysHeaderBuilder_;
      /**
       * <pre>
       *定义第1个属性，SysHeader类型
       * </pre>
       *
       * <code>optional .com.pinkpig.entity.protobuf.SysHeader sysHeader = 1;</code>
       */
      public boolean hasSysHeader() {
        return sysHeaderBuilder_ != null || sysHeader_ != null;
      }
      /**
       * <pre>
       *定义第1个属性，SysHeader类型
       * </pre>
       *
       * <code>optional .com.pinkpig.entity.protobuf.SysHeader sysHeader = 1;</code>
       */
      public com.pinkpig.entity.protobuf.MessageProto.SysHeader getSysHeader() {
        if (sysHeaderBuilder_ == null) {
          return sysHeader_ == null ? com.pinkpig.entity.protobuf.MessageProto.SysHeader.getDefaultInstance() : sysHeader_;
        } else {
          return sysHeaderBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *定义第1个属性，SysHeader类型
       * </pre>
       *
       * <code>optional .com.pinkpig.entity.protobuf.SysHeader sysHeader = 1;</code>
       */
      public Builder setSysHeader(com.pinkpig.entity.protobuf.MessageProto.SysHeader value) {
        if (sysHeaderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sysHeader_ = value;
          onChanged();
        } else {
          sysHeaderBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *定义第1个属性，SysHeader类型
       * </pre>
       *
       * <code>optional .com.pinkpig.entity.protobuf.SysHeader sysHeader = 1;</code>
       */
      public Builder setSysHeader(
          com.pinkpig.entity.protobuf.MessageProto.SysHeader.Builder builderForValue) {
        if (sysHeaderBuilder_ == null) {
          sysHeader_ = builderForValue.build();
          onChanged();
        } else {
          sysHeaderBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *定义第1个属性，SysHeader类型
       * </pre>
       *
       * <code>optional .com.pinkpig.entity.protobuf.SysHeader sysHeader = 1;</code>
       */
      public Builder mergeSysHeader(com.pinkpig.entity.protobuf.MessageProto.SysHeader value) {
        if (sysHeaderBuilder_ == null) {
          if (sysHeader_ != null) {
            sysHeader_ =
              com.pinkpig.entity.protobuf.MessageProto.SysHeader.newBuilder(sysHeader_).mergeFrom(value).buildPartial();
          } else {
            sysHeader_ = value;
          }
          onChanged();
        } else {
          sysHeaderBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *定义第1个属性，SysHeader类型
       * </pre>
       *
       * <code>optional .com.pinkpig.entity.protobuf.SysHeader sysHeader = 1;</code>
       */
      public Builder clearSysHeader() {
        if (sysHeaderBuilder_ == null) {
          sysHeader_ = null;
          onChanged();
        } else {
          sysHeader_ = null;
          sysHeaderBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *定义第1个属性，SysHeader类型
       * </pre>
       *
       * <code>optional .com.pinkpig.entity.protobuf.SysHeader sysHeader = 1;</code>
       */
      public com.pinkpig.entity.protobuf.MessageProto.SysHeader.Builder getSysHeaderBuilder() {
        
        onChanged();
        return getSysHeaderFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *定义第1个属性，SysHeader类型
       * </pre>
       *
       * <code>optional .com.pinkpig.entity.protobuf.SysHeader sysHeader = 1;</code>
       */
      public com.pinkpig.entity.protobuf.MessageProto.SysHeaderOrBuilder getSysHeaderOrBuilder() {
        if (sysHeaderBuilder_ != null) {
          return sysHeaderBuilder_.getMessageOrBuilder();
        } else {
          return sysHeader_ == null ?
              com.pinkpig.entity.protobuf.MessageProto.SysHeader.getDefaultInstance() : sysHeader_;
        }
      }
      /**
       * <pre>
       *定义第1个属性，SysHeader类型
       * </pre>
       *
       * <code>optional .com.pinkpig.entity.protobuf.SysHeader sysHeader = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.pinkpig.entity.protobuf.MessageProto.SysHeader, com.pinkpig.entity.protobuf.MessageProto.SysHeader.Builder, com.pinkpig.entity.protobuf.MessageProto.SysHeaderOrBuilder> 
          getSysHeaderFieldBuilder() {
        if (sysHeaderBuilder_ == null) {
          sysHeaderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.pinkpig.entity.protobuf.MessageProto.SysHeader, com.pinkpig.entity.protobuf.MessageProto.SysHeader.Builder, com.pinkpig.entity.protobuf.MessageProto.SysHeaderOrBuilder>(
                  getSysHeader(),
                  getParentForChildren(),
                  isClean());
          sysHeader_ = null;
        }
        return sysHeaderBuilder_;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *定义第2个属性，字节数组类型
       * </pre>
       *
       * <code>optional bytes content = 2;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <pre>
       *定义第2个属性，字节数组类型
       * </pre>
       *
       * <code>optional bytes content = 2;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *定义第2个属性，字节数组类型
       * </pre>
       *
       * <code>optional bytes content = 2;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.pinkpig.entity.protobuf.MessageData)
    }

    // @@protoc_insertion_point(class_scope:com.pinkpig.entity.protobuf.MessageData)
    private static final com.pinkpig.entity.protobuf.MessageProto.MessageData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.pinkpig.entity.protobuf.MessageProto.MessageData();
    }

    public static com.pinkpig.entity.protobuf.MessageProto.MessageData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageData>
        PARSER = new com.google.protobuf.AbstractParser<MessageData>() {
      public MessageData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MessageData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageData> getParserForType() {
      return PARSER;
    }

    public com.pinkpig.entity.protobuf.MessageProto.MessageData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SysHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.pinkpig.entity.protobuf.SysHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string bizSeqNo = 1;</code>
     */
    java.lang.String getBizSeqNo();
    /**
     * <code>optional string bizSeqNo = 1;</code>
     */
    com.google.protobuf.ByteString
        getBizSeqNoBytes();

    /**
     * <code>optional string sysSeqNo = 2;</code>
     */
    java.lang.String getSysSeqNo();
    /**
     * <code>optional string sysSeqNo = 2;</code>
     */
    com.google.protobuf.ByteString
        getSysSeqNoBytes();

    /**
     * <code>optional string ip = 3;</code>
     */
    java.lang.String getIp();
    /**
     * <code>optional string ip = 3;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>optional string userId = 4;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>optional string userId = 4;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>optional int32 version = 5;</code>
     */
    int getVersion();

    /**
     * <code>optional string channelId = 6;</code>
     */
    java.lang.String getChannelId();
    /**
     * <code>optional string channelId = 6;</code>
     */
    com.google.protobuf.ByteString
        getChannelIdBytes();

    /**
     * <code>optional string origSysId = 7;</code>
     */
    java.lang.String getOrigSysId();
    /**
     * <code>optional string origSysId = 7;</code>
     */
    com.google.protobuf.ByteString
        getOrigSysIdBytes();

    /**
     * <code>optional string prevSysId = 8;</code>
     */
    java.lang.String getPrevSysId();
    /**
     * <code>optional string prevSysId = 8;</code>
     */
    com.google.protobuf.ByteString
        getPrevSysIdBytes();
  }
  /**
   * Protobuf type {@code com.pinkpig.entity.protobuf.SysHeader}
   */
  public  static final class SysHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.pinkpig.entity.protobuf.SysHeader)
      SysHeaderOrBuilder {
    // Use SysHeader.newBuilder() to construct.
    private SysHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SysHeader() {
      bizSeqNo_ = "";
      sysSeqNo_ = "";
      ip_ = "";
      userId_ = "";
      version_ = 0;
      channelId_ = "";
      origSysId_ = "";
      prevSysId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SysHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              bizSeqNo_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              sysSeqNo_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 40: {

              version_ = input.readInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              channelId_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              origSysId_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              prevSysId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pinkpig.entity.protobuf.MessageProto.internal_static_com_pinkpig_entity_protobuf_SysHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pinkpig.entity.protobuf.MessageProto.internal_static_com_pinkpig_entity_protobuf_SysHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pinkpig.entity.protobuf.MessageProto.SysHeader.class, com.pinkpig.entity.protobuf.MessageProto.SysHeader.Builder.class);
    }

    public static final int BIZSEQNO_FIELD_NUMBER = 1;
    private volatile java.lang.Object bizSeqNo_;
    /**
     * <code>optional string bizSeqNo = 1;</code>
     */
    public java.lang.String getBizSeqNo() {
      java.lang.Object ref = bizSeqNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bizSeqNo_ = s;
        return s;
      }
    }
    /**
     * <code>optional string bizSeqNo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBizSeqNoBytes() {
      java.lang.Object ref = bizSeqNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bizSeqNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SYSSEQNO_FIELD_NUMBER = 2;
    private volatile java.lang.Object sysSeqNo_;
    /**
     * <code>optional string sysSeqNo = 2;</code>
     */
    public java.lang.String getSysSeqNo() {
      java.lang.Object ref = sysSeqNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sysSeqNo_ = s;
        return s;
      }
    }
    /**
     * <code>optional string sysSeqNo = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSysSeqNoBytes() {
      java.lang.Object ref = sysSeqNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sysSeqNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 3;
    private volatile java.lang.Object ip_;
    /**
     * <code>optional string ip = 3;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ip = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 4;
    private volatile java.lang.Object userId_;
    /**
     * <code>optional string userId = 4;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 5;
    private int version_;
    /**
     * <code>optional int32 version = 5;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int CHANNELID_FIELD_NUMBER = 6;
    private volatile java.lang.Object channelId_;
    /**
     * <code>optional string channelId = 6;</code>
     */
    public java.lang.String getChannelId() {
      java.lang.Object ref = channelId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        channelId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string channelId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getChannelIdBytes() {
      java.lang.Object ref = channelId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORIGSYSID_FIELD_NUMBER = 7;
    private volatile java.lang.Object origSysId_;
    /**
     * <code>optional string origSysId = 7;</code>
     */
    public java.lang.String getOrigSysId() {
      java.lang.Object ref = origSysId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        origSysId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string origSysId = 7;</code>
     */
    public com.google.protobuf.ByteString
        getOrigSysIdBytes() {
      java.lang.Object ref = origSysId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        origSysId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PREVSYSID_FIELD_NUMBER = 8;
    private volatile java.lang.Object prevSysId_;
    /**
     * <code>optional string prevSysId = 8;</code>
     */
    public java.lang.String getPrevSysId() {
      java.lang.Object ref = prevSysId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        prevSysId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string prevSysId = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPrevSysIdBytes() {
      java.lang.Object ref = prevSysId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        prevSysId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getBizSeqNoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, bizSeqNo_);
      }
      if (!getSysSeqNoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sysSeqNo_);
      }
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ip_);
      }
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userId_);
      }
      if (version_ != 0) {
        output.writeInt32(5, version_);
      }
      if (!getChannelIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, channelId_);
      }
      if (!getOrigSysIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, origSysId_);
      }
      if (!getPrevSysIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, prevSysId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getBizSeqNoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, bizSeqNo_);
      }
      if (!getSysSeqNoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sysSeqNo_);
      }
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ip_);
      }
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userId_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, version_);
      }
      if (!getChannelIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, channelId_);
      }
      if (!getOrigSysIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, origSysId_);
      }
      if (!getPrevSysIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, prevSysId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.pinkpig.entity.protobuf.MessageProto.SysHeader)) {
        return super.equals(obj);
      }
      com.pinkpig.entity.protobuf.MessageProto.SysHeader other = (com.pinkpig.entity.protobuf.MessageProto.SysHeader) obj;

      boolean result = true;
      result = result && getBizSeqNo()
          .equals(other.getBizSeqNo());
      result = result && getSysSeqNo()
          .equals(other.getSysSeqNo());
      result = result && getIp()
          .equals(other.getIp());
      result = result && getUserId()
          .equals(other.getUserId());
      result = result && (getVersion()
          == other.getVersion());
      result = result && getChannelId()
          .equals(other.getChannelId());
      result = result && getOrigSysId()
          .equals(other.getOrigSysId());
      result = result && getPrevSysId()
          .equals(other.getPrevSysId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + BIZSEQNO_FIELD_NUMBER;
      hash = (53 * hash) + getBizSeqNo().hashCode();
      hash = (37 * hash) + SYSSEQNO_FIELD_NUMBER;
      hash = (53 * hash) + getSysSeqNo().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + CHANNELID_FIELD_NUMBER;
      hash = (53 * hash) + getChannelId().hashCode();
      hash = (37 * hash) + ORIGSYSID_FIELD_NUMBER;
      hash = (53 * hash) + getOrigSysId().hashCode();
      hash = (37 * hash) + PREVSYSID_FIELD_NUMBER;
      hash = (53 * hash) + getPrevSysId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.pinkpig.entity.protobuf.MessageProto.SysHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pinkpig.entity.protobuf.MessageProto.SysHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pinkpig.entity.protobuf.MessageProto.SysHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pinkpig.entity.protobuf.MessageProto.SysHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pinkpig.entity.protobuf.MessageProto.SysHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pinkpig.entity.protobuf.MessageProto.SysHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pinkpig.entity.protobuf.MessageProto.SysHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.pinkpig.entity.protobuf.MessageProto.SysHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pinkpig.entity.protobuf.MessageProto.SysHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pinkpig.entity.protobuf.MessageProto.SysHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.pinkpig.entity.protobuf.MessageProto.SysHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.pinkpig.entity.protobuf.SysHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.pinkpig.entity.protobuf.SysHeader)
        com.pinkpig.entity.protobuf.MessageProto.SysHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pinkpig.entity.protobuf.MessageProto.internal_static_com_pinkpig_entity_protobuf_SysHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pinkpig.entity.protobuf.MessageProto.internal_static_com_pinkpig_entity_protobuf_SysHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pinkpig.entity.protobuf.MessageProto.SysHeader.class, com.pinkpig.entity.protobuf.MessageProto.SysHeader.Builder.class);
      }

      // Construct using com.pinkpig.entity.protobuf.MessageProto.SysHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        bizSeqNo_ = "";

        sysSeqNo_ = "";

        ip_ = "";

        userId_ = "";

        version_ = 0;

        channelId_ = "";

        origSysId_ = "";

        prevSysId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pinkpig.entity.protobuf.MessageProto.internal_static_com_pinkpig_entity_protobuf_SysHeader_descriptor;
      }

      public com.pinkpig.entity.protobuf.MessageProto.SysHeader getDefaultInstanceForType() {
        return com.pinkpig.entity.protobuf.MessageProto.SysHeader.getDefaultInstance();
      }

      public com.pinkpig.entity.protobuf.MessageProto.SysHeader build() {
        com.pinkpig.entity.protobuf.MessageProto.SysHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pinkpig.entity.protobuf.MessageProto.SysHeader buildPartial() {
        com.pinkpig.entity.protobuf.MessageProto.SysHeader result = new com.pinkpig.entity.protobuf.MessageProto.SysHeader(this);
        result.bizSeqNo_ = bizSeqNo_;
        result.sysSeqNo_ = sysSeqNo_;
        result.ip_ = ip_;
        result.userId_ = userId_;
        result.version_ = version_;
        result.channelId_ = channelId_;
        result.origSysId_ = origSysId_;
        result.prevSysId_ = prevSysId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pinkpig.entity.protobuf.MessageProto.SysHeader) {
          return mergeFrom((com.pinkpig.entity.protobuf.MessageProto.SysHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pinkpig.entity.protobuf.MessageProto.SysHeader other) {
        if (other == com.pinkpig.entity.protobuf.MessageProto.SysHeader.getDefaultInstance()) return this;
        if (!other.getBizSeqNo().isEmpty()) {
          bizSeqNo_ = other.bizSeqNo_;
          onChanged();
        }
        if (!other.getSysSeqNo().isEmpty()) {
          sysSeqNo_ = other.sysSeqNo_;
          onChanged();
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (!other.getChannelId().isEmpty()) {
          channelId_ = other.channelId_;
          onChanged();
        }
        if (!other.getOrigSysId().isEmpty()) {
          origSysId_ = other.origSysId_;
          onChanged();
        }
        if (!other.getPrevSysId().isEmpty()) {
          prevSysId_ = other.prevSysId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pinkpig.entity.protobuf.MessageProto.SysHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pinkpig.entity.protobuf.MessageProto.SysHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object bizSeqNo_ = "";
      /**
       * <code>optional string bizSeqNo = 1;</code>
       */
      public java.lang.String getBizSeqNo() {
        java.lang.Object ref = bizSeqNo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bizSeqNo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string bizSeqNo = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBizSeqNoBytes() {
        java.lang.Object ref = bizSeqNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bizSeqNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string bizSeqNo = 1;</code>
       */
      public Builder setBizSeqNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bizSeqNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string bizSeqNo = 1;</code>
       */
      public Builder clearBizSeqNo() {
        
        bizSeqNo_ = getDefaultInstance().getBizSeqNo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string bizSeqNo = 1;</code>
       */
      public Builder setBizSeqNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bizSeqNo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sysSeqNo_ = "";
      /**
       * <code>optional string sysSeqNo = 2;</code>
       */
      public java.lang.String getSysSeqNo() {
        java.lang.Object ref = sysSeqNo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sysSeqNo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sysSeqNo = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSysSeqNoBytes() {
        java.lang.Object ref = sysSeqNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sysSeqNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sysSeqNo = 2;</code>
       */
      public Builder setSysSeqNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sysSeqNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sysSeqNo = 2;</code>
       */
      public Builder clearSysSeqNo() {
        
        sysSeqNo_ = getDefaultInstance().getSysSeqNo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sysSeqNo = 2;</code>
       */
      public Builder setSysSeqNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sysSeqNo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>optional string ip = 3;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ip = 3;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ip = 3;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 3;</code>
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 3;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>optional string userId = 4;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userId = 4;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 4;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 4;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>optional int32 version = 5;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>optional int32 version = 5;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 version = 5;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object channelId_ = "";
      /**
       * <code>optional string channelId = 6;</code>
       */
      public java.lang.String getChannelId() {
        java.lang.Object ref = channelId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          channelId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string channelId = 6;</code>
       */
      public com.google.protobuf.ByteString
          getChannelIdBytes() {
        java.lang.Object ref = channelId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          channelId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string channelId = 6;</code>
       */
      public Builder setChannelId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        channelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string channelId = 6;</code>
       */
      public Builder clearChannelId() {
        
        channelId_ = getDefaultInstance().getChannelId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string channelId = 6;</code>
       */
      public Builder setChannelIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        channelId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object origSysId_ = "";
      /**
       * <code>optional string origSysId = 7;</code>
       */
      public java.lang.String getOrigSysId() {
        java.lang.Object ref = origSysId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          origSysId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string origSysId = 7;</code>
       */
      public com.google.protobuf.ByteString
          getOrigSysIdBytes() {
        java.lang.Object ref = origSysId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          origSysId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string origSysId = 7;</code>
       */
      public Builder setOrigSysId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        origSysId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string origSysId = 7;</code>
       */
      public Builder clearOrigSysId() {
        
        origSysId_ = getDefaultInstance().getOrigSysId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string origSysId = 7;</code>
       */
      public Builder setOrigSysIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        origSysId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object prevSysId_ = "";
      /**
       * <code>optional string prevSysId = 8;</code>
       */
      public java.lang.String getPrevSysId() {
        java.lang.Object ref = prevSysId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          prevSysId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string prevSysId = 8;</code>
       */
      public com.google.protobuf.ByteString
          getPrevSysIdBytes() {
        java.lang.Object ref = prevSysId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          prevSysId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string prevSysId = 8;</code>
       */
      public Builder setPrevSysId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        prevSysId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string prevSysId = 8;</code>
       */
      public Builder clearPrevSysId() {
        
        prevSysId_ = getDefaultInstance().getPrevSysId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string prevSysId = 8;</code>
       */
      public Builder setPrevSysIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        prevSysId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.pinkpig.entity.protobuf.SysHeader)
    }

    // @@protoc_insertion_point(class_scope:com.pinkpig.entity.protobuf.SysHeader)
    private static final com.pinkpig.entity.protobuf.MessageProto.SysHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.pinkpig.entity.protobuf.MessageProto.SysHeader();
    }

    public static com.pinkpig.entity.protobuf.MessageProto.SysHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SysHeader>
        PARSER = new com.google.protobuf.AbstractParser<SysHeader>() {
      public SysHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SysHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SysHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SysHeader> getParserForType() {
      return PARSER;
    }

    public com.pinkpig.entity.protobuf.MessageProto.SysHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pinkpig_entity_protobuf_MessageData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_pinkpig_entity_protobuf_MessageData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pinkpig_entity_protobuf_SysHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_pinkpig_entity_protobuf_SysHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MessageData.proto\022\033com.pinkpig.entity." +
      "protobuf\"Y\n\013MessageData\0229\n\tsysHeader\030\001 \001" +
      "(\0132&.com.pinkpig.entity.protobuf.SysHead" +
      "er\022\017\n\007content\030\002 \001(\014\"\225\001\n\tSysHeader\022\020\n\010biz" +
      "SeqNo\030\001 \001(\t\022\020\n\010sysSeqNo\030\002 \001(\t\022\n\n\002ip\030\003 \001(" +
      "\t\022\016\n\006userId\030\004 \001(\t\022\017\n\007version\030\005 \001(\005\022\021\n\tch" +
      "annelId\030\006 \001(\t\022\021\n\torigSysId\030\007 \001(\t\022\021\n\tprev" +
      "SysId\030\010 \001(\tB\016B\014MessageProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_pinkpig_entity_protobuf_MessageData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_pinkpig_entity_protobuf_MessageData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_pinkpig_entity_protobuf_MessageData_descriptor,
        new java.lang.String[] { "SysHeader", "Content", });
    internal_static_com_pinkpig_entity_protobuf_SysHeader_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_pinkpig_entity_protobuf_SysHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_pinkpig_entity_protobuf_SysHeader_descriptor,
        new java.lang.String[] { "BizSeqNo", "SysSeqNo", "Ip", "UserId", "Version", "ChannelId", "OrigSysId", "PrevSysId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
