// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderInfo.proto

package com.pinkpig.entity.protobuf;

public final class OrderInfoProto {
  private OrderInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrderInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.pinkpig.entity.protobuf.OrderInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string orderId = 1;</code>
     */
    java.lang.String getOrderId();
    /**
     * <code>optional string orderId = 1;</code>
     */
    com.google.protobuf.ByteString
        getOrderIdBytes();

    /**
     * <code>optional string userId = 2;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>optional string userId = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>optional double orderPrice = 3;</code>
     */
    double getOrderPrice();

    /**
     * <code>optional double deliveryPrice = 4;</code>
     */
    double getDeliveryPrice();

    /**
     * <code>optional double discountPrice = 5;</code>
     */
    double getDiscountPrice();

    /**
     * <code>optional string orderDatetime = 6;</code>
     */
    java.lang.String getOrderDatetime();
    /**
     * <code>optional string orderDatetime = 6;</code>
     */
    com.google.protobuf.ByteString
        getOrderDatetimeBytes();

    /**
     * <code>optional string payMethod = 7;</code>
     */
    java.lang.String getPayMethod();
    /**
     * <code>optional string payMethod = 7;</code>
     */
    com.google.protobuf.ByteString
        getPayMethodBytes();

    /**
     * <code>optional string payDatetime = 8;</code>
     */
    java.lang.String getPayDatetime();
    /**
     * <code>optional string payDatetime = 8;</code>
     */
    com.google.protobuf.ByteString
        getPayDatetimeBytes();

    /**
     * <code>optional string deliveryMethod = 9;</code>
     */
    java.lang.String getDeliveryMethod();
    /**
     * <code>optional string deliveryMethod = 9;</code>
     */
    com.google.protobuf.ByteString
        getDeliveryMethodBytes();

    /**
     * <code>optional string receiverName = 10;</code>
     */
    java.lang.String getReceiverName();
    /**
     * <code>optional string receiverName = 10;</code>
     */
    com.google.protobuf.ByteString
        getReceiverNameBytes();

    /**
     * <code>optional string receiverAddress = 11;</code>
     */
    java.lang.String getReceiverAddress();
    /**
     * <code>optional string receiverAddress = 11;</code>
     */
    com.google.protobuf.ByteString
        getReceiverAddressBytes();

    /**
     * <code>optional string receiverPhone = 12;</code>
     */
    java.lang.String getReceiverPhone();
    /**
     * <code>optional string receiverPhone = 12;</code>
     */
    com.google.protobuf.ByteString
        getReceiverPhoneBytes();

    /**
     * <code>optional string remark = 99;</code>
     */
    java.lang.String getRemark();
    /**
     * <code>optional string remark = 99;</code>
     */
    com.google.protobuf.ByteString
        getRemarkBytes();
  }
  /**
   * Protobuf type {@code com.pinkpig.entity.protobuf.OrderInfo}
   */
  public  static final class OrderInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.pinkpig.entity.protobuf.OrderInfo)
      OrderInfoOrBuilder {
    // Use OrderInfo.newBuilder() to construct.
    private OrderInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OrderInfo() {
      orderId_ = "";
      userId_ = "";
      orderPrice_ = 0D;
      deliveryPrice_ = 0D;
      discountPrice_ = 0D;
      orderDatetime_ = "";
      payMethod_ = "";
      payDatetime_ = "";
      deliveryMethod_ = "";
      receiverName_ = "";
      receiverAddress_ = "";
      receiverPhone_ = "";
      remark_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private OrderInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              orderId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 25: {

              orderPrice_ = input.readDouble();
              break;
            }
            case 33: {

              deliveryPrice_ = input.readDouble();
              break;
            }
            case 41: {

              discountPrice_ = input.readDouble();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              orderDatetime_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              payMethod_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              payDatetime_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              deliveryMethod_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              receiverName_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              receiverAddress_ = s;
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              receiverPhone_ = s;
              break;
            }
            case 794: {
              java.lang.String s = input.readStringRequireUtf8();

              remark_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pinkpig.entity.protobuf.OrderInfoProto.internal_static_com_pinkpig_entity_protobuf_OrderInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pinkpig.entity.protobuf.OrderInfoProto.internal_static_com_pinkpig_entity_protobuf_OrderInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo.class, com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo.Builder.class);
    }

    public static final int ORDERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object orderId_;
    /**
     * <code>optional string orderId = 1;</code>
     */
    public java.lang.String getOrderId() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string orderId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOrderIdBytes() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private volatile java.lang.Object userId_;
    /**
     * <code>optional string userId = 2;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDERPRICE_FIELD_NUMBER = 3;
    private double orderPrice_;
    /**
     * <code>optional double orderPrice = 3;</code>
     */
    public double getOrderPrice() {
      return orderPrice_;
    }

    public static final int DELIVERYPRICE_FIELD_NUMBER = 4;
    private double deliveryPrice_;
    /**
     * <code>optional double deliveryPrice = 4;</code>
     */
    public double getDeliveryPrice() {
      return deliveryPrice_;
    }

    public static final int DISCOUNTPRICE_FIELD_NUMBER = 5;
    private double discountPrice_;
    /**
     * <code>optional double discountPrice = 5;</code>
     */
    public double getDiscountPrice() {
      return discountPrice_;
    }

    public static final int ORDERDATETIME_FIELD_NUMBER = 6;
    private volatile java.lang.Object orderDatetime_;
    /**
     * <code>optional string orderDatetime = 6;</code>
     */
    public java.lang.String getOrderDatetime() {
      java.lang.Object ref = orderDatetime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderDatetime_ = s;
        return s;
      }
    }
    /**
     * <code>optional string orderDatetime = 6;</code>
     */
    public com.google.protobuf.ByteString
        getOrderDatetimeBytes() {
      java.lang.Object ref = orderDatetime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderDatetime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYMETHOD_FIELD_NUMBER = 7;
    private volatile java.lang.Object payMethod_;
    /**
     * <code>optional string payMethod = 7;</code>
     */
    public java.lang.String getPayMethod() {
      java.lang.Object ref = payMethod_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        payMethod_ = s;
        return s;
      }
    }
    /**
     * <code>optional string payMethod = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPayMethodBytes() {
      java.lang.Object ref = payMethod_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payMethod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYDATETIME_FIELD_NUMBER = 8;
    private volatile java.lang.Object payDatetime_;
    /**
     * <code>optional string payDatetime = 8;</code>
     */
    public java.lang.String getPayDatetime() {
      java.lang.Object ref = payDatetime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        payDatetime_ = s;
        return s;
      }
    }
    /**
     * <code>optional string payDatetime = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPayDatetimeBytes() {
      java.lang.Object ref = payDatetime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payDatetime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DELIVERYMETHOD_FIELD_NUMBER = 9;
    private volatile java.lang.Object deliveryMethod_;
    /**
     * <code>optional string deliveryMethod = 9;</code>
     */
    public java.lang.String getDeliveryMethod() {
      java.lang.Object ref = deliveryMethod_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deliveryMethod_ = s;
        return s;
      }
    }
    /**
     * <code>optional string deliveryMethod = 9;</code>
     */
    public com.google.protobuf.ByteString
        getDeliveryMethodBytes() {
      java.lang.Object ref = deliveryMethod_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deliveryMethod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVERNAME_FIELD_NUMBER = 10;
    private volatile java.lang.Object receiverName_;
    /**
     * <code>optional string receiverName = 10;</code>
     */
    public java.lang.String getReceiverName() {
      java.lang.Object ref = receiverName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string receiverName = 10;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverNameBytes() {
      java.lang.Object ref = receiverName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVERADDRESS_FIELD_NUMBER = 11;
    private volatile java.lang.Object receiverAddress_;
    /**
     * <code>optional string receiverAddress = 11;</code>
     */
    public java.lang.String getReceiverAddress() {
      java.lang.Object ref = receiverAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverAddress_ = s;
        return s;
      }
    }
    /**
     * <code>optional string receiverAddress = 11;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverAddressBytes() {
      java.lang.Object ref = receiverAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVERPHONE_FIELD_NUMBER = 12;
    private volatile java.lang.Object receiverPhone_;
    /**
     * <code>optional string receiverPhone = 12;</code>
     */
    public java.lang.String getReceiverPhone() {
      java.lang.Object ref = receiverPhone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverPhone_ = s;
        return s;
      }
    }
    /**
     * <code>optional string receiverPhone = 12;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverPhoneBytes() {
      java.lang.Object ref = receiverPhone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverPhone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REMARK_FIELD_NUMBER = 99;
    private volatile java.lang.Object remark_;
    /**
     * <code>optional string remark = 99;</code>
     */
    public java.lang.String getRemark() {
      java.lang.Object ref = remark_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        remark_ = s;
        return s;
      }
    }
    /**
     * <code>optional string remark = 99;</code>
     */
    public com.google.protobuf.ByteString
        getRemarkBytes() {
      java.lang.Object ref = remark_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getOrderIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, orderId_);
      }
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userId_);
      }
      if (orderPrice_ != 0D) {
        output.writeDouble(3, orderPrice_);
      }
      if (deliveryPrice_ != 0D) {
        output.writeDouble(4, deliveryPrice_);
      }
      if (discountPrice_ != 0D) {
        output.writeDouble(5, discountPrice_);
      }
      if (!getOrderDatetimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, orderDatetime_);
      }
      if (!getPayMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, payMethod_);
      }
      if (!getPayDatetimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, payDatetime_);
      }
      if (!getDeliveryMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, deliveryMethod_);
      }
      if (!getReceiverNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, receiverName_);
      }
      if (!getReceiverAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, receiverAddress_);
      }
      if (!getReceiverPhoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, receiverPhone_);
      }
      if (!getRemarkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 99, remark_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getOrderIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, orderId_);
      }
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userId_);
      }
      if (orderPrice_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, orderPrice_);
      }
      if (deliveryPrice_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, deliveryPrice_);
      }
      if (discountPrice_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, discountPrice_);
      }
      if (!getOrderDatetimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, orderDatetime_);
      }
      if (!getPayMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, payMethod_);
      }
      if (!getPayDatetimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, payDatetime_);
      }
      if (!getDeliveryMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, deliveryMethod_);
      }
      if (!getReceiverNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, receiverName_);
      }
      if (!getReceiverAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, receiverAddress_);
      }
      if (!getReceiverPhoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, receiverPhone_);
      }
      if (!getRemarkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(99, remark_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo)) {
        return super.equals(obj);
      }
      com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo other = (com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo) obj;

      boolean result = true;
      result = result && getOrderId()
          .equals(other.getOrderId());
      result = result && getUserId()
          .equals(other.getUserId());
      result = result && (
          java.lang.Double.doubleToLongBits(getOrderPrice())
          == java.lang.Double.doubleToLongBits(
              other.getOrderPrice()));
      result = result && (
          java.lang.Double.doubleToLongBits(getDeliveryPrice())
          == java.lang.Double.doubleToLongBits(
              other.getDeliveryPrice()));
      result = result && (
          java.lang.Double.doubleToLongBits(getDiscountPrice())
          == java.lang.Double.doubleToLongBits(
              other.getDiscountPrice()));
      result = result && getOrderDatetime()
          .equals(other.getOrderDatetime());
      result = result && getPayMethod()
          .equals(other.getPayMethod());
      result = result && getPayDatetime()
          .equals(other.getPayDatetime());
      result = result && getDeliveryMethod()
          .equals(other.getDeliveryMethod());
      result = result && getReceiverName()
          .equals(other.getReceiverName());
      result = result && getReceiverAddress()
          .equals(other.getReceiverAddress());
      result = result && getReceiverPhone()
          .equals(other.getReceiverPhone());
      result = result && getRemark()
          .equals(other.getRemark());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ORDERID_FIELD_NUMBER;
      hash = (53 * hash) + getOrderId().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + ORDERPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getOrderPrice()));
      hash = (37 * hash) + DELIVERYPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDeliveryPrice()));
      hash = (37 * hash) + DISCOUNTPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDiscountPrice()));
      hash = (37 * hash) + ORDERDATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getOrderDatetime().hashCode();
      hash = (37 * hash) + PAYMETHOD_FIELD_NUMBER;
      hash = (53 * hash) + getPayMethod().hashCode();
      hash = (37 * hash) + PAYDATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getPayDatetime().hashCode();
      hash = (37 * hash) + DELIVERYMETHOD_FIELD_NUMBER;
      hash = (53 * hash) + getDeliveryMethod().hashCode();
      hash = (37 * hash) + RECEIVERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverName().hashCode();
      hash = (37 * hash) + RECEIVERADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverAddress().hashCode();
      hash = (37 * hash) + RECEIVERPHONE_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverPhone().hashCode();
      hash = (37 * hash) + REMARK_FIELD_NUMBER;
      hash = (53 * hash) + getRemark().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.pinkpig.entity.protobuf.OrderInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.pinkpig.entity.protobuf.OrderInfo)
        com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pinkpig.entity.protobuf.OrderInfoProto.internal_static_com_pinkpig_entity_protobuf_OrderInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pinkpig.entity.protobuf.OrderInfoProto.internal_static_com_pinkpig_entity_protobuf_OrderInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo.class, com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo.Builder.class);
      }

      // Construct using com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        orderId_ = "";

        userId_ = "";

        orderPrice_ = 0D;

        deliveryPrice_ = 0D;

        discountPrice_ = 0D;

        orderDatetime_ = "";

        payMethod_ = "";

        payDatetime_ = "";

        deliveryMethod_ = "";

        receiverName_ = "";

        receiverAddress_ = "";

        receiverPhone_ = "";

        remark_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pinkpig.entity.protobuf.OrderInfoProto.internal_static_com_pinkpig_entity_protobuf_OrderInfo_descriptor;
      }

      public com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo getDefaultInstanceForType() {
        return com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo.getDefaultInstance();
      }

      public com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo build() {
        com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo buildPartial() {
        com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo result = new com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo(this);
        result.orderId_ = orderId_;
        result.userId_ = userId_;
        result.orderPrice_ = orderPrice_;
        result.deliveryPrice_ = deliveryPrice_;
        result.discountPrice_ = discountPrice_;
        result.orderDatetime_ = orderDatetime_;
        result.payMethod_ = payMethod_;
        result.payDatetime_ = payDatetime_;
        result.deliveryMethod_ = deliveryMethod_;
        result.receiverName_ = receiverName_;
        result.receiverAddress_ = receiverAddress_;
        result.receiverPhone_ = receiverPhone_;
        result.remark_ = remark_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo) {
          return mergeFrom((com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo other) {
        if (other == com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo.getDefaultInstance()) return this;
        if (!other.getOrderId().isEmpty()) {
          orderId_ = other.orderId_;
          onChanged();
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (other.getOrderPrice() != 0D) {
          setOrderPrice(other.getOrderPrice());
        }
        if (other.getDeliveryPrice() != 0D) {
          setDeliveryPrice(other.getDeliveryPrice());
        }
        if (other.getDiscountPrice() != 0D) {
          setDiscountPrice(other.getDiscountPrice());
        }
        if (!other.getOrderDatetime().isEmpty()) {
          orderDatetime_ = other.orderDatetime_;
          onChanged();
        }
        if (!other.getPayMethod().isEmpty()) {
          payMethod_ = other.payMethod_;
          onChanged();
        }
        if (!other.getPayDatetime().isEmpty()) {
          payDatetime_ = other.payDatetime_;
          onChanged();
        }
        if (!other.getDeliveryMethod().isEmpty()) {
          deliveryMethod_ = other.deliveryMethod_;
          onChanged();
        }
        if (!other.getReceiverName().isEmpty()) {
          receiverName_ = other.receiverName_;
          onChanged();
        }
        if (!other.getReceiverAddress().isEmpty()) {
          receiverAddress_ = other.receiverAddress_;
          onChanged();
        }
        if (!other.getReceiverPhone().isEmpty()) {
          receiverPhone_ = other.receiverPhone_;
          onChanged();
        }
        if (!other.getRemark().isEmpty()) {
          remark_ = other.remark_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object orderId_ = "";
      /**
       * <code>optional string orderId = 1;</code>
       */
      public java.lang.String getOrderId() {
        java.lang.Object ref = orderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string orderId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOrderIdBytes() {
        java.lang.Object ref = orderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string orderId = 1;</code>
       */
      public Builder setOrderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string orderId = 1;</code>
       */
      public Builder clearOrderId() {
        
        orderId_ = getDefaultInstance().getOrderId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string orderId = 1;</code>
       */
      public Builder setOrderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>optional string userId = 2;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userId = 2;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 2;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 2;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private double orderPrice_ ;
      /**
       * <code>optional double orderPrice = 3;</code>
       */
      public double getOrderPrice() {
        return orderPrice_;
      }
      /**
       * <code>optional double orderPrice = 3;</code>
       */
      public Builder setOrderPrice(double value) {
        
        orderPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double orderPrice = 3;</code>
       */
      public Builder clearOrderPrice() {
        
        orderPrice_ = 0D;
        onChanged();
        return this;
      }

      private double deliveryPrice_ ;
      /**
       * <code>optional double deliveryPrice = 4;</code>
       */
      public double getDeliveryPrice() {
        return deliveryPrice_;
      }
      /**
       * <code>optional double deliveryPrice = 4;</code>
       */
      public Builder setDeliveryPrice(double value) {
        
        deliveryPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double deliveryPrice = 4;</code>
       */
      public Builder clearDeliveryPrice() {
        
        deliveryPrice_ = 0D;
        onChanged();
        return this;
      }

      private double discountPrice_ ;
      /**
       * <code>optional double discountPrice = 5;</code>
       */
      public double getDiscountPrice() {
        return discountPrice_;
      }
      /**
       * <code>optional double discountPrice = 5;</code>
       */
      public Builder setDiscountPrice(double value) {
        
        discountPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double discountPrice = 5;</code>
       */
      public Builder clearDiscountPrice() {
        
        discountPrice_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object orderDatetime_ = "";
      /**
       * <code>optional string orderDatetime = 6;</code>
       */
      public java.lang.String getOrderDatetime() {
        java.lang.Object ref = orderDatetime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderDatetime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string orderDatetime = 6;</code>
       */
      public com.google.protobuf.ByteString
          getOrderDatetimeBytes() {
        java.lang.Object ref = orderDatetime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderDatetime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string orderDatetime = 6;</code>
       */
      public Builder setOrderDatetime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderDatetime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string orderDatetime = 6;</code>
       */
      public Builder clearOrderDatetime() {
        
        orderDatetime_ = getDefaultInstance().getOrderDatetime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string orderDatetime = 6;</code>
       */
      public Builder setOrderDatetimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderDatetime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object payMethod_ = "";
      /**
       * <code>optional string payMethod = 7;</code>
       */
      public java.lang.String getPayMethod() {
        java.lang.Object ref = payMethod_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          payMethod_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string payMethod = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPayMethodBytes() {
        java.lang.Object ref = payMethod_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          payMethod_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string payMethod = 7;</code>
       */
      public Builder setPayMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payMethod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string payMethod = 7;</code>
       */
      public Builder clearPayMethod() {
        
        payMethod_ = getDefaultInstance().getPayMethod();
        onChanged();
        return this;
      }
      /**
       * <code>optional string payMethod = 7;</code>
       */
      public Builder setPayMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        payMethod_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object payDatetime_ = "";
      /**
       * <code>optional string payDatetime = 8;</code>
       */
      public java.lang.String getPayDatetime() {
        java.lang.Object ref = payDatetime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          payDatetime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string payDatetime = 8;</code>
       */
      public com.google.protobuf.ByteString
          getPayDatetimeBytes() {
        java.lang.Object ref = payDatetime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          payDatetime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string payDatetime = 8;</code>
       */
      public Builder setPayDatetime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payDatetime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string payDatetime = 8;</code>
       */
      public Builder clearPayDatetime() {
        
        payDatetime_ = getDefaultInstance().getPayDatetime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string payDatetime = 8;</code>
       */
      public Builder setPayDatetimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        payDatetime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object deliveryMethod_ = "";
      /**
       * <code>optional string deliveryMethod = 9;</code>
       */
      public java.lang.String getDeliveryMethod() {
        java.lang.Object ref = deliveryMethod_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deliveryMethod_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string deliveryMethod = 9;</code>
       */
      public com.google.protobuf.ByteString
          getDeliveryMethodBytes() {
        java.lang.Object ref = deliveryMethod_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deliveryMethod_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string deliveryMethod = 9;</code>
       */
      public Builder setDeliveryMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deliveryMethod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string deliveryMethod = 9;</code>
       */
      public Builder clearDeliveryMethod() {
        
        deliveryMethod_ = getDefaultInstance().getDeliveryMethod();
        onChanged();
        return this;
      }
      /**
       * <code>optional string deliveryMethod = 9;</code>
       */
      public Builder setDeliveryMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deliveryMethod_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiverName_ = "";
      /**
       * <code>optional string receiverName = 10;</code>
       */
      public java.lang.String getReceiverName() {
        java.lang.Object ref = receiverName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiverName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string receiverName = 10;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverNameBytes() {
        java.lang.Object ref = receiverName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiverName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string receiverName = 10;</code>
       */
      public Builder setReceiverName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiverName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string receiverName = 10;</code>
       */
      public Builder clearReceiverName() {
        
        receiverName_ = getDefaultInstance().getReceiverName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string receiverName = 10;</code>
       */
      public Builder setReceiverNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiverName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiverAddress_ = "";
      /**
       * <code>optional string receiverAddress = 11;</code>
       */
      public java.lang.String getReceiverAddress() {
        java.lang.Object ref = receiverAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiverAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string receiverAddress = 11;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverAddressBytes() {
        java.lang.Object ref = receiverAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiverAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string receiverAddress = 11;</code>
       */
      public Builder setReceiverAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiverAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string receiverAddress = 11;</code>
       */
      public Builder clearReceiverAddress() {
        
        receiverAddress_ = getDefaultInstance().getReceiverAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string receiverAddress = 11;</code>
       */
      public Builder setReceiverAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiverAddress_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiverPhone_ = "";
      /**
       * <code>optional string receiverPhone = 12;</code>
       */
      public java.lang.String getReceiverPhone() {
        java.lang.Object ref = receiverPhone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiverPhone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string receiverPhone = 12;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverPhoneBytes() {
        java.lang.Object ref = receiverPhone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiverPhone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string receiverPhone = 12;</code>
       */
      public Builder setReceiverPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiverPhone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string receiverPhone = 12;</code>
       */
      public Builder clearReceiverPhone() {
        
        receiverPhone_ = getDefaultInstance().getReceiverPhone();
        onChanged();
        return this;
      }
      /**
       * <code>optional string receiverPhone = 12;</code>
       */
      public Builder setReceiverPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiverPhone_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object remark_ = "";
      /**
       * <code>optional string remark = 99;</code>
       */
      public java.lang.String getRemark() {
        java.lang.Object ref = remark_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          remark_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string remark = 99;</code>
       */
      public com.google.protobuf.ByteString
          getRemarkBytes() {
        java.lang.Object ref = remark_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          remark_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string remark = 99;</code>
       */
      public Builder setRemark(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        remark_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string remark = 99;</code>
       */
      public Builder clearRemark() {
        
        remark_ = getDefaultInstance().getRemark();
        onChanged();
        return this;
      }
      /**
       * <code>optional string remark = 99;</code>
       */
      public Builder setRemarkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        remark_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.pinkpig.entity.protobuf.OrderInfo)
    }

    // @@protoc_insertion_point(class_scope:com.pinkpig.entity.protobuf.OrderInfo)
    private static final com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo();
    }

    public static com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderInfo>
        PARSER = new com.google.protobuf.AbstractParser<OrderInfo>() {
      public OrderInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new OrderInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OrderInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OrderInfo> getParserForType() {
      return PARSER;
    }

    public com.pinkpig.entity.protobuf.OrderInfoProto.OrderInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pinkpig_entity_protobuf_OrderInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_pinkpig_entity_protobuf_OrderInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017OrderInfo.proto\022\033com.pinkpig.entity.pr" +
      "otobuf\"\233\002\n\tOrderInfo\022\017\n\007orderId\030\001 \001(\t\022\016\n" +
      "\006userId\030\002 \001(\t\022\022\n\norderPrice\030\003 \001(\001\022\025\n\rdel" +
      "iveryPrice\030\004 \001(\001\022\025\n\rdiscountPrice\030\005 \001(\001\022" +
      "\025\n\rorderDatetime\030\006 \001(\t\022\021\n\tpayMethod\030\007 \001(" +
      "\t\022\023\n\013payDatetime\030\010 \001(\t\022\026\n\016deliveryMethod" +
      "\030\t \001(\t\022\024\n\014receiverName\030\n \001(\t\022\027\n\017receiver" +
      "Address\030\013 \001(\t\022\025\n\rreceiverPhone\030\014 \001(\t\022\016\n\006" +
      "remark\030c \001(\tB\020B\016OrderInfoProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_pinkpig_entity_protobuf_OrderInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_pinkpig_entity_protobuf_OrderInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_pinkpig_entity_protobuf_OrderInfo_descriptor,
        new java.lang.String[] { "OrderId", "UserId", "OrderPrice", "DeliveryPrice", "DiscountPrice", "OrderDatetime", "PayMethod", "PayDatetime", "DeliveryMethod", "ReceiverName", "ReceiverAddress", "ReceiverPhone", "Remark", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
